[package]
name = "bls-style-digest"
version = "0.1.0"
edition = "2021"

[dependencies]
digest = "0.10"
generic-ec = { version = "0.4.5", features = ["serde", "curve-secp256k1", "hash-to-scalar"] }
generic-ec-zkp = "0.4"
key-share = "0.5"
rand_core = { version = "0.6", default-features = false }
rand_hash = { version = "0.1" }
round-based = { version = "0.4", features = ["derive"] }
serde = "1"
sha2 = "0.10"
thiserror = { version = "2" }
udigest = { version = "0.2", default-features = false, features = ["inline-struct", "derive"] }

k256 = { version = "0.13", features = ["hash2curve"] }
generic-ec-curves = { version = "0.2.4", features = ["rust-crypto"] }

[dev-dependencies]
generic-ec = { version = "0.4.5", features = ["curve-ed25519"] }
key-share = { version = "0.5", features = ["spof"] }
rand = "0.8"
rand_dev = "0.1"
round-based = { version = "0.4", features = ["sim"] }
test-case = "3"
